=begin
#ChronoSheets API

#<div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for ChronoSheetsAPI::FileAttachmentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FileAttachmentsApi' do
  before do
    # run before each test
    @instance = ChronoSheetsAPI::FileAttachmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileAttachmentsApi' do
    it 'should create an instance of FileAttachmentsApi' do
      expect(@instance).to be_instance_of(ChronoSheetsAPI::FileAttachmentsApi)
    end
  end

  # unit tests for file_attachments_get_my_file_attachments
  # Get my file attachments.  Get files you&#39;ve attached to timesheets.
  # 
  # @param start_date The Start date of the date range.  File attachments after this date will be obtained.
  # @param end_date The End date of the date range.  File attachments before this date will be obtained.
  # @param skip Skip this many File attachments
  # @param take Take this many File attachments
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CSApiResponseForPaginatedListTimesheetFileAttachment]
  describe 'file_attachments_get_my_file_attachments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
