=begin
#ChronoSheets API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TimesheetsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TimesheetsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TimesheetsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimesheetsApi' do
    it 'should create an instance of TimesheetsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TimesheetsApi)
    end
  end

  # unit tests for timesheets_create_single_timesheet
  # Inserts a single timesheet record
  # 
  # @param request The timesheet request object
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CsApiApiResponseInt32]
  describe 'timesheets_create_single_timesheet test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for timesheets_delete_timesheet
  # Delete a timesheet
  # 
  # @param timesheet_id The ID of the timesheet to delete
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CsApiApiResponseBoolean]
  describe 'timesheets_delete_timesheet test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for timesheets_get_timesheets
  # Get timesheets between start and end dates
  # 
  # @param start_date The start date of the date range
  # @param end_date The end date of the date range
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CsApiApiResponseListTimesheet]
  describe 'timesheets_get_timesheets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for timesheets_update_timesheets
  # Batch update timesheets
  # 
  # @param request The batch update timesheets request
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CsApiApiResponseListInt32]
  describe 'timesheets_update_timesheets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
