=begin
#The ChronoSheets API

#<div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TripsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TripsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TripsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TripsApi' do
    it 'should create an instance of TripsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TripsApi)
    end
  end

  # unit tests for trips_create_trip
  # Create a new trip.  Important: create a timesheet record before calling this, passing in the new timesheet record id as a reference.    Requires the &#39;SubmitTimesheets&#39; permission.
  # 
  # @param request A Create Trip Request object containing values for the new Trip to create
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CSApiResponseInt32]
  describe 'trips_create_trip test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for trips_get_my_trip_by_id
  # Get trip by Id.    Requires the &#39;ViewMyTrips&#39; permission.
  # 
  # @param trip_id The ID of the Trip you want to get
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CSApiResponseTrip]
  describe 'trips_get_my_trip_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for trips_get_my_trips
  # Get my trips.  Get the GPS trips you&#39;ve recorded and submitted.    Requires the &#39;ViewMyTrips&#39; permission.
  # 
  # @param start_date The Start date of the date range.  Trips after this date will be obtained.
  # @param end_date The End date of the date range.  Trips before this date will be obtained.
  # @param skip Skip this many Trips
  # @param take Take this many Trips
  # @param vehicle_id Filter by a particular Vehicle (get trips made with a particular vehicle), specified by VehicleId
  # @param x_chronosheets_auth The ChronoSheets Auth Token
  # @param [Hash] opts the optional parameters
  # @return [CSApiResponseForPaginatedListTrip]
  describe 'trips_get_my_trips test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
