=begin
#ChronoSheets API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::CsApiUserJobFavourite
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CsApiUserJobFavourite' do
  before do
    # run before each test
    @instance = SwaggerClient::CsApiUserJobFavourite.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CsApiUserJobFavourite' do
    it 'should create an instance of CsApiUserJobFavourite' do
      expect(@instance).to be_instance_of(SwaggerClient::CsApiUserJobFavourite)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "job_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

